### ISSUE TITLE
REST API requirements 

### ISSUE THREAD

**Issue by Gillian0023** [MusicConnectionMachine/RelationshipsG4#32]
I have started our API requirements in  https://docs.google.com/document/d/1TjBtrBpeD-v0Q_oqy_b2sM1i8mfR1qLu6cwPUkP8BBk/edit, something will be changed after the Q&A session

**Comment by simonzachau** [comment]
thanks for starting, @Gillian0023 ! The Q&A session might also help us to gather requests from group @MusicConnectionMachine/group-5 and @MusicConnectionMachine/group-6 
I imagine we should adjust the json so that it fits the use cases better, e.g. skip some unnecessary information openIE is giving us (like the "span" elements):
### openIE result:
```
{
"subject": "Beethoven",
"subjectSpan": [4,5],
"relation": "was taught by",
"relationSpan": [5,8],
"object": "Beethoven father Johann van Beethoven",
"objectSpan": [4,13]
}
```
### my proposal for our JSON result:
```
{
"subject": id,
"relation": "taught",
"object": id,
}
```

**Comment by sacdallago** [comment]
Please move this issue to [the api] repo, use a form like [here](https://github.com/MusicConnectionMachine/api/issues/1#issue-214357513)
